services:
  slidev:
    image: tangramor/slidev:latest
    user: node
    volumes:
      - ${PWD}:/slidev
    ports:
      - 3030:3030
    environment:
      - NPM_MIRROR=https://registry.npmmirror.com